export const listCategoryBadge: any = [
  { uuid: 'aa', name: 'Training Badges' },
  { uuid: 'bb', name: 'Ami Badges' },
  { uuid: 'cc', name: 'Education Badges' },
]
export const listCategoryGallery: any = [
  { uuid: 'aa', name: 'Institutional' },
  { uuid: 'bb', name: 'Public Organizations' },
  { uuid: 'cc', name: 'Enterprise' },
  { uuid: 'dd', name: 'Organizations' },
  { uuid: 'ee', name: 'Entertainment' },
  { uuid: 'ff', name: 'Other' },
]
export const listBadges: any = [
  {
    name: '1 시험',
    id: '1',
    jwt: '1',
    img: 'https://picsum.photos/id/1/200',
    published: '마카니 체인버스',
    expiredDate: '2024/04/01',
    categoryId: 'aa',
    tag: [
      { id: 1, label: '인공지능/Artificial Intelligence', value: 'ai' },
      { id: 2, label: '확장현실/Augmented Reality', value: 'ar' },
      { id: 3, label: '블록체인/Blockchain', value: 'blockchain' },
      { id: 4, label: '빅데이터/Big Data', value: 'bigdata' },
    ],
  },
  {
    name: '2 시험',
    id: '2',
    jwt: '2',
    img: 'https://picsum.photos/id/2/200',
    published: '마카니 체인버스',
    expiredDate: '2024/04/02',
    categoryId: 'bb',
    tag: [
      { id: 1, label: '인공지능/Artificial Intelligence', value: 'ai' },
      { id: 2, label: '확장현실/Augmented Reality', value: 'ar' },
      { id: 3, label: '블록체인/Blockchain', value: 'blockchain' },
      { id: 4, label: '빅데이터/Big Data', value: 'bigdata' },
    ],
  },
  {
    name: '3 시험',
    id: '3',
    jwt: '3',
    img: 'https://picsum.photos/id/3/200',
    published: '마카니 체인버스',
    expiredDate: '2024/04/03',
    categoryId: 'cc',
    tag: [
      { id: 1, label: '인공지능/Artificial Intelligence', value: 'ai' },
      { id: 2, label: '확장현실/Augmented Reality', value: 'ar' },
      { id: 3, label: '블록체인/Blockchain', value: 'blockchain' },
      { id: 4, label: '빅데이터/Big Data', value: 'bigdata' },
    ],
  },
  {
    name: '4 시험',
    id: '4',
    jwt: '4',
    img: 'https://picsum.photos/id/4/200',
    published: '마카니 체인버스',
    expiredDate: '2024/04/04',
    categoryId: 'bb',
    tag: [
      { id: 1, label: '인공지능/Artificial Intelligence', value: 'ai' },
      { id: 2, label: '확장현실/Augmented Reality', value: 'ar' },
      { id: 3, label: '블록체인/Blockchain', value: 'blockchain' },
      { id: 4, label: '빅데이터/Big Data', value: 'bigdata' },
    ],
  },
  {
    name: '5 시험',
    id: '5',
    jwt: '5',
    img: 'https://picsum.photos/id/5/200',
    published: '마카니 체인버스',
    expiredDate: '2024/04/05',
    categoryId: 'aa',
    tag: [
      { id: 1, label: '인공지능/Artificial Intelligence', value: 'ai' },
      { id: 2, label: '확장현실/Augmented Reality', value: 'ar' },
      { id: 3, label: '블록체인/Blockchain', value: 'blockchain' },
      { id: 4, label: '빅데이터/Big Data', value: 'bigdata' },
    ],
  },
  {
    name: '6 시험',
    id: '6',
    jwt: '6',
    img: 'https://picsum.photos/id/6/200',
    published: '마카니 체인버스',
    expiredDate: '2024/04/06',
    categoryId: 'bb',
    tag: [
      { id: 1, label: '인공지능/Artificial Intelligence', value: 'ai' },
      { id: 2, label: '확장현실/Augmented Reality', value: 'ar' },
      { id: 3, label: '블록체인/Blockchain', value: 'blockchain' },
      { id: 4, label: '빅데이터/Big Data', value: 'bigdata' },
    ],
  },
  {
    name: '7 시험',
    id: '7',
    jwt: '7',
    img: 'https://picsum.photos/id/7/200',
    published: '마카니 체인버스',
    expiredDate: '2024/04/07',
    categoryId: 'cc',
    tag: [
      { id: 1, label: '인공지능/Artificial Intelligence', value: 'ai' },
      { id: 2, label: '확장현실/Augmented Reality', value: 'ar' },
      { id: 3, label: '블록체인/Blockchain', value: 'blockchain' },
      { id: 4, label: '빅데이터/Big Data', value: 'bigdata' },
    ],
  },
  {
    name: '8 시험',
    id: '8',
    jwt: '8',
    img: 'https://picsum.photos/id/8/200',
    published: '마카니 체인버스',
    expiredDate: '2024/04/08',
    categoryId: 'cc',
    tag: [
      { id: 1, label: '인공지능/Artificial Intelligence', value: 'ai' },
      { id: 2, label: '확장현실/Augmented Reality', value: 'ar' },
      { id: 3, label: '블록체인/Blockchain', value: 'blockchain' },
      { id: 4, label: '빅데이터/Big Data', value: 'bigdata' },
    ],
  },
]

export const listPublisher: any = [
  {
    uuid: 'aa',
    name: '마카니 체인버스',
    img: 'https://picsum.photos/id/1/200',
    title: 'Recruitment of the Future Convergence Academy',
  },
  {
    uuid: 'bb',
    name: 'Adobe',
    img: 'https://picsum.photos/id/2/200',
    title: 'Submit Open Badges registered by the demand source',
  },
  {
    uuid: 'cc',
    name: 'Microsoft',
    img: 'https://picsum.photos/id/3/200',
    title: 'Recruitment of the Future Convergence Academy',
  },
  {
    uuid: 'dd',
    name: 'Harvard University',
    img: 'https://picsum.photos/id/4/200',
    title: 'Submit Open Badges registered by the demand source',
  },
  {
    uuid: 'ee',
    name: 'Oxford University',
    img: 'https://picsum.photos/id/5/200',
    title: 'Recruitment of the Future Convergence Academy',
  },
  {
    uuid: 'ff',
    name: 'Amazon Web Services, Inc.',
    img: 'https://picsum.photos/id/6/200',
    title: 'Submit Open Badges registered by the demand source',
  },
]
